# Generated by Django 3.2b1 on 2021-06-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='kilo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='randevu',
            name='yas',
            field=models.IntegerField(default=1),
        ),
    ]
