# Generated by Django 3.2b1 on 2021-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0002_auto_20210626_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='time',
            field=models.TimeField(),
        ),
    ]
