# Generated by Django 3.2b1 on 2021-06-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0004_randevu_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='randevu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randevu.randevu'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
