# Generated by Django 3.2b1 on 2021-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0005_auto_20210626_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
