# Generated by Django 3.2b1 on 2021-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0006_alter_order_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='month',
        ),
        migrations.AddField(
            model_name='randevu',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='status',
            field=models.CharField(choices=[('Odeme Yapildi', 'Odeme Yapildi'), ('Odeme Yapilmadi', 'Odeme Yapilmadi')], default='Odeme Yapilmadi', max_length=20),
        ),
    ]
