# Generated by Django 3.2b1 on 2021-06-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0007_auto_20210626_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='month',
        ),
    ]
